#!/usr/bin/env python3
import os
import re
import subprocess
import sys

# Define base directories relative to the script's root
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

INCLUDE_DIR = os.path.join(PROJECT_ROOT, "include")
SRC_DIR = os.path.join(PROJECT_ROOT, "src")
OUTPUT_FILE = os.path.join(PROJECT_ROOT, "main.c")

# Pre-defined topological ordering to avoid forward declaration/type issues
HEADER_ORDER = [
    "types.h",
    "admin.h",
    "product.h",
    "bundle.h",
    "order.h",
    "file_io.h",
    "utils.h",
    "menu.h",
]

SRC_ORDER = [
    "admin.c",
    "bundle.c",
    "file_io.c",
    "menu.c",
    "order.c",
    "product.c",
    "utils.c",
    "program.c",
]


def main():
    print("Starting automated code bundling process...")

    # 1. Collect all unique standard includes <...>
    std_includes = set()
    include_pattern = re.compile(r"^\s*#include\s*<([^>]+)>")
    local_include_pattern = re.compile(r'^\s*#include\s*"([^"]+)"')

    # Read standard includes from headers
    for h in HEADER_ORDER:
        h_path = os.path.join(INCLUDE_DIR, h)
        if not os.path.isfile(h_path):
            print(f"Error: Header file {h_path} not found.")
            sys.exit(1)
        with open(h_path, "r", encoding="utf-8") as f:
            for line in f:
                match = include_pattern.match(line)
                if match:
                    std_includes.add(match.group(1))

    # Read standard includes from sources
    for s in SRC_ORDER:
        s_path = os.path.join(SRC_DIR, s)
        if not os.path.isfile(s_path):
            print(f"Error: Source file {s_path} not found.")
            sys.exit(1)
        with open(s_path, "r", encoding="utf-8") as f:
            for line in f:
                match = include_pattern.match(line)
                if match:
                    std_includes.add(match.group(1))

    # 2. Build the bundled file content
    bundled_lines = []
    # bundled_lines.append("// =========================================================")
    # bundled_lines.append("// BUNDLED C FILE - AUTOMATICALLY GENERATED BY BUNDLE.PY")
    # bundled_lines.append("// =========================================================")
    # bundled_lines.append("")

    # Write consolidated standard library headers
    for lib in sorted(std_includes):
        bundled_lines.append(f"#include <{lib}>")
    bundled_lines.append("")

    # 3. Process each header file
    for h in HEADER_ORDER:
        h_path = os.path.join(INCLUDE_DIR, h)
        # bundled_lines.append(f"// --- Header: {h} ---")
        with open(h_path, "r", encoding="utf-8") as f:
            for line in f:
                # Strip standard and local include lines
                if include_pattern.match(line) or local_include_pattern.match(line):
                    continue
                bundled_lines.append(line.rstrip("\n"))
        bundled_lines.append("")

    # 4. Process each source file
    for s in SRC_ORDER:
        s_path = os.path.join(SRC_DIR, s)
        # banner_name = "Main Source: program.c" if s == "program.c" else f"Source: {s}"
        # bundled_lines.append(f"// --- {banner_name} ---")
        with open(s_path, "r", encoding="utf-8") as f:
            for line in f:
                # Strip standard and local include lines
                if include_pattern.match(line) or local_include_pattern.match(line):
                    continue
                bundled_lines.append(line.rstrip("\n"))
        bundled_lines.append("")

    # Write to main.c
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(bundled_lines) + "\n")

    print(f"Bundled successfully into: {OUTPUT_FILE}")

    # 5. Run clang-format if available
    # try:
    #     print("Running clang-format on main.c...")
    #     subprocess.run(["clang-format", "-i", OUTPUT_FILE], check=True)
    #     print("Formatting complete.")
    # except Exception as e:
    #     print(f"Warning: Could not run clang-format: {e}")


if __name__ == "__main__":
    main()
